### PR TITLE
Watcher 1.5

### PR DESCRIPTION
**Pull request by ghost**
i managed to have it working on 1.11/Watcher 1.5
everything seems to be working fine, though im not 100% sure

### CODE REVIEW

**Comment by M4rbleL1ne** [comment]
I'm working on this myself, you just fixed compilation errors and some hooks but not the rest.
